# Generated by Django 4.1.4 on 2023-01-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='grade',
            new_name='department',
        ),
    ]
